import type { KnownLocale } from '../types';

export interface CategoryUi {
  useTool: string;
  openTool: string;
  exploreRoute: string;
  missionLabel: string;
  catalogLabel: string;
  observationEyebrow: string;
  toolIndexLabel: string;
  fieldNotesLabel: string;
  fieldNotesTitle: string;
  relatedEyebrow: string;
  moreToolsIn: string;
  zoom: string;
  zoomControls: string;
  zoomOut: string;
  resetZoom: string;
  zoomIn: string;
  breadcrumb: string;
}

export const CATEGORY_UI: Record<KnownLocale, CategoryUi> = {
  es: { useTool: 'Usar herramienta', openTool: 'Abrir herramienta', exploreRoute: 'Apuntar al siguiente', missionLabel: 'Objetivo de observación', catalogLabel: 'estrellas', observationEyebrow: 'Cuaderno de observación · 01', toolIndexLabel: 'Todas las estrellas', fieldNotesLabel: 'Notas de campo', fieldNotesTitle: 'Para cuando el cielo pide más tiempo', relatedEyebrow: 'Sigue explorando', moreToolsIn: 'Más herramientas en', zoom: 'Zoom', zoomControls: 'Controles de zoom', zoomOut: 'Reducir zoom', resetZoom: 'Restablecer zoom', zoomIn: 'Aumentar zoom', breadcrumb: 'Migas de pan' },
  en: { useTool: 'Use tool', openTool: 'Open tool', exploreRoute: 'Point to next', missionLabel: 'Observation target', catalogLabel: 'stars', observationEyebrow: 'Observation log · 01', toolIndexLabel: 'All stars', fieldNotesLabel: 'Field notes', fieldNotesTitle: 'For when the sky asks for more time', relatedEyebrow: 'Keep exploring', moreToolsIn: 'More tools in', zoom: 'Zoom', zoomControls: 'Zoom controls', zoomOut: 'Zoom out', resetZoom: 'Reset zoom', zoomIn: 'Zoom in', breadcrumb: 'Breadcrumb' },
  fr: { useTool: "Utiliser l'outil", openTool: "Ouvrir l'outil", exploreRoute: 'Pointer vers la suivante', missionLabel: "Cible d'observation", catalogLabel: 'étoiles', observationEyebrow: "Carnet d'observation · 01", toolIndexLabel: 'Toutes les étoiles', fieldNotesLabel: 'Notes de terrain', fieldNotesTitle: 'Quand le ciel demande plus de temps', relatedEyebrow: 'Continuez à explorer', moreToolsIn: "Plus d'outils dans", zoom: 'Zoom', zoomControls: 'Commandes de zoom', zoomOut: 'Réduire zoom', resetZoom: 'Réinitialiser le zoom', zoomIn: 'Augmenter zoom', breadcrumb: 'Fil d’Ariane' },
  de: { useTool: 'Werkzeug verwenden', openTool: 'Werkzeug öffnen', exploreRoute: 'Nächsten anpeilen', missionLabel: 'Beobachtungsziel', catalogLabel: 'Sterne', observationEyebrow: 'Beobachtungsnotiz · 01', toolIndexLabel: 'Alle Sterne', fieldNotesLabel: 'Feldnotizen', fieldNotesTitle: 'Wenn der Himmel nach mehr Zeit verlangt', relatedEyebrow: 'Mehr entdecken', moreToolsIn: 'Weitere Werkzeuge in', zoom: 'Zoom', zoomControls: 'Zoom-Steuerung', zoomOut: 'Verkleinern', resetZoom: 'Zoom zurücksetzen', zoomIn: 'Vergrößern', breadcrumb: 'Brotkrümelnavigation' },
  it: { useTool: 'Usa lo strumento', openTool: 'Apri lo strumento', exploreRoute: 'Punta alla prossima', missionLabel: 'Obiettivo di osservazione', catalogLabel: 'stelle', observationEyebrow: 'Diario di osservazione · 01', toolIndexLabel: 'Tutte le stelle', fieldNotesLabel: 'Note di campo', fieldNotesTitle: 'Quando il cielo chiede più tempo', relatedEyebrow: 'Continua a esplorare', moreToolsIn: 'Altri strumenti in', zoom: 'Zoom', zoomControls: 'Controlli zoom', zoomOut: 'Riduci zoom', resetZoom: 'Reimposta zoom', zoomIn: 'Aumenta zoom', breadcrumb: 'Breadcrumb' },
  pt: { useTool: 'Usar ferramenta', openTool: 'Abrir ferramenta', exploreRoute: 'Apontar para a próxima', missionLabel: 'Alvo de observação', catalogLabel: 'estrelas', observationEyebrow: 'Diário de observação · 01', toolIndexLabel: 'Todas as estrelas', fieldNotesLabel: 'Notas de campo', fieldNotesTitle: 'Quando o céu pede mais tempo', relatedEyebrow: 'Continue a explorar', moreToolsIn: 'Mais ferramentas em', zoom: 'Zoom', zoomControls: 'Controlos de zoom', zoomOut: 'Reduzir zoom', resetZoom: 'Repor zoom', zoomIn: 'Aumentar zoom', breadcrumb: 'Trilho de navegação' },
  nl: { useTool: 'Tool gebruiken', openTool: 'Tool openen', exploreRoute: 'Volgende aanwijzen', missionLabel: 'Observatiedoel', catalogLabel: 'sterren', observationEyebrow: 'Observatienotitie · 01', toolIndexLabel: 'Alle sterren', fieldNotesLabel: 'Veldnotities', fieldNotesTitle: 'Wanneer de hemel om meer tijd vraagt', relatedEyebrow: 'Blijf ontdekken', moreToolsIn: 'Meer tools in', zoom: 'Zoom', zoomControls: 'Zoomknoppen', zoomOut: 'Uitzoomen', resetZoom: 'Zoom herstellen', zoomIn: 'Inzoomen', breadcrumb: 'Broodkruimelnavigatie' },
  sv: { useTool: 'Använd verktyget', openTool: 'Öppna verktyget', exploreRoute: 'Peka på nästa', missionLabel: 'Observationsmål', catalogLabel: 'stjärnor', observationEyebrow: 'Observationslogg · 01', toolIndexLabel: 'Alla stjärnor', fieldNotesLabel: 'Fältanteckningar', fieldNotesTitle: 'När himlen ber om mer tid', relatedEyebrow: 'Utforska mer', moreToolsIn: 'Fler verktyg i', zoom: 'Zoom', zoomControls: 'Zoomkontroller', zoomOut: 'Zooma ut', resetZoom: 'Återställ zoom', zoomIn: 'Zooma in', breadcrumb: 'Brödsmulenavigering' },
  pl: { useTool: 'Użyj narzędzia', openTool: 'Otwórz narzędzie', exploreRoute: 'Wskaż następną', missionLabel: 'Cel obserwacji', catalogLabel: 'gwiazd', observationEyebrow: 'Dziennik obserwacji · 01', toolIndexLabel: 'Wszystkie gwiazdy', fieldNotesLabel: 'Notatki terenowe', fieldNotesTitle: 'Gdy niebo prosi o więcej czasu', relatedEyebrow: 'Odkrywaj dalej', moreToolsIn: 'Więcej narzędzi w', zoom: 'Powiększenie', zoomControls: 'Sterowanie powiększeniem', zoomOut: 'Pomniejsz', resetZoom: 'Resetuj powiększenie', zoomIn: 'Powiększ', breadcrumb: 'Okruszki nawigacji' },
  id: { useTool: 'Gunakan alat', openTool: 'Buka alat', exploreRoute: 'Arahkan ke berikutnya', missionLabel: 'Target pengamatan', catalogLabel: 'bintang', observationEyebrow: 'Catatan pengamatan · 01', toolIndexLabel: 'Semua bintang', fieldNotesLabel: 'Catatan lapangan', fieldNotesTitle: 'Saat langit meminta lebih banyak waktu', relatedEyebrow: 'Jelajahi lebih lanjut', moreToolsIn: 'Alat lainnya di', zoom: 'Zoom', zoomControls: 'Kontrol zoom', zoomOut: 'Perkecil', resetZoom: 'Atur ulang zoom', zoomIn: 'Perbesar', breadcrumb: 'Breadcrumb' },
  tr: { useTool: 'Aracı kullan', openTool: 'Aracı aç', exploreRoute: 'Sonrakine yönel', missionLabel: 'Gözlem hedefi', catalogLabel: 'yıldız', observationEyebrow: 'Gözlem günlüğü · 01', toolIndexLabel: 'Tüm yıldızlar', fieldNotesLabel: 'Saha notları', fieldNotesTitle: 'Gökyüzü daha fazla zaman istediğinde', relatedEyebrow: 'Keşfetmeye devam edin', moreToolsIn: 'Diğer araçlar:', zoom: 'Yakınlaştırma', zoomControls: 'Yakınlaştırma denetimleri', zoomOut: 'Uzaklaştır', resetZoom: 'Yakınlaştırmayı sıfırla', zoomIn: 'Yakınlaştır', breadcrumb: 'İçerik haritası' },
  ru: { useTool: 'Использовать инструмент', openTool: 'Открыть инструмент', exploreRoute: 'Навести на следующую', missionLabel: 'Цель наблюдения', catalogLabel: 'звёзд', observationEyebrow: 'Журнал наблюдений · 01', toolIndexLabel: 'Все звёзды', fieldNotesLabel: 'Полевые заметки', fieldNotesTitle: 'Когда небо просит больше времени', relatedEyebrow: 'Продолжить изучение', moreToolsIn: 'Другие инструменты в', zoom: 'Масштаб', zoomControls: 'Управление масштабом', zoomOut: 'Уменьшить', resetZoom: 'Сбросить масштаб', zoomIn: 'Увеличить', breadcrumb: 'Навигационная цепочка' },
  ja: { useTool: 'ツールを使う', openTool: 'ツールを開く', exploreRoute: '次へ向ける', missionLabel: '観測対象', catalogLabel: '星', observationEyebrow: '観測ノート · 01', toolIndexLabel: 'すべての星', fieldNotesLabel: 'フィールドノート', fieldNotesTitle: '空がもっと時間を求めるとき', relatedEyebrow: 'さらに探索', moreToolsIn: 'その他のツール：', zoom: 'ズーム', zoomControls: 'ズーム操作', zoomOut: '縮小', resetZoom: 'ズームをリセット', zoomIn: '拡大', breadcrumb: 'パンくずリスト' },
  ko: { useTool: '도구 사용', openTool: '도구 열기', exploreRoute: '다음 별 가리키기', missionLabel: '관측 대상', catalogLabel: '별', observationEyebrow: '관측 기록 · 01', toolIndexLabel: '모든 별', fieldNotesLabel: '현장 기록', fieldNotesTitle: '하늘이 더 많은 시간을 요구할 때', relatedEyebrow: '더 탐색하기', moreToolsIn: '카테고리의 다른 도구:', zoom: '확대/축소', zoomControls: '확대/축소 컨트롤', zoomOut: '축소', resetZoom: '확대/축소 초기화', zoomIn: '확대', breadcrumb: '탐색 경로' },
  zh: { useTool: '使用工具', openTool: '打开工具', exploreRoute: '指向下一颗', missionLabel: '观测目标', catalogLabel: '颗星', observationEyebrow: '观测记录 · 01', toolIndexLabel: '所有星辰', fieldNotesLabel: '观测笔记', fieldNotesTitle: '当夜空需要更多时间', relatedEyebrow: '继续探索', moreToolsIn: '更多工具：', zoom: '缩放', zoomControls: '缩放控件', zoomOut: '缩小', resetZoom: '重置缩放', zoomIn: '放大', breadcrumb: '面包屑导航' },
};

export const getCategoryUi = (locale: KnownLocale): CategoryUi => CATEGORY_UI[locale];
