import { createLocalizedContent } from '../localized';

export const content = createLocalizedContent({
  slug: "planner-astrofotografie-belichtingsstapeling",
  title: "Planner voor belichtingsstapeling in astrofotografie",
  description: "Plan astrofotografiesessies met NPF en de 500 regel, het aantal frames, totale integratie en werkelijke tijd in het veld.",
  ui: {
    cameraLegend: "Camerageometrie", focalLabel: "Brandpuntsafstand", focalHelp: "Brandpuntsafstand van lens of telescoop in mm", apertureLabel: "Diafragma", apertureHelp: "Gebruik het f getal, bijvoorbeeld 2,8", pixelPitchLabel: "Pixelpitch", pixelPitchHelp: "Fysieke grootte van de fotosite in micrometer", declinationLabel: "Declinatie van doel", declinationHelp: "Absolute declinatie in graden", sensorLabel: "Sensorformaat", sensorOptions: { fullFrame: "Full frame", apsC: "APS C", microFourThirds: "Micro Four Thirds", phone: "Telefoonsensor" },
    ruleLabel: "Belichtingslimiet", ruleNpf: "NPF formule", rule500: "500 regel", trackingLabel: "Status montering", untracked: "Zonder tracking", tracked: "Trackingmontering", trackingExposureLabel: "Belichting per gevolgd frame", trackingExposureHelp: "Alleen gebruikt met een trackingmontering. Begin met 30 tot 120 s en controleer testframes.", deadTimeLabel: "Dode tijd tussen frames", deadTimeHelp: "Begin met ongeveer 2 s en pas aan voor buffer, kaartschrijven en interval.", totalIntegrationLabel: "Gewenste totale integratie", totalIntegrationHelp: "De nuttige belichtingstijd die je wilt verzamelen", resultTitle: "Je opnameplan", resultKicker: "Een startpunt voor de nacht", secondsUnit: "per frame", framesLabel: "frames", totalTimeLabel: "Geplande integratie", sessionTimeLabel: "Geschatte veldtijd", gainLabel: "Ideale stackingwinst", sessionDetail: "Inclusief {dead} tussen frames: {deadTotal} intervaltijd.", workloadText: "{frames} sluiterbewegingen. De veldschatting bevat de dode tijd tussen frames.", highWorkloadText: "{frames} sluiterbewegingen. Overweeg elektronische sluiter, extra accu's en opslag. Geschatte veldtijd: {session}.", sensorPixelWarning: "Controleer de cameraspecificatie: {pixel} is groot voor APS C en kan de NPF limiet verkorten.", comparisonTitle: "Twee limieten, één keuze", npfLabel: "NPF limiet", rule500Label: "Limiet van de 500 regel", deltaLabel: "NPF verschil", timelineTitle: "De stack als lichtstrook", timelineStart: "eerste frame", timelineEnd: "laatste frame", trackingNote: "Tracking is actief. Het plan gebruikt {ceiling} per frame, dus {frames} frames en ongeveer {session} in het veld. Controleer deze duur met uitlijning, guiding en een testframe; NPF blijft de vergelijking zonder tracking.", untrackedNote: "Gebruik {ceiling} als startlimiet en bekijk een testframe op volledige resolutie voor stervorm en hemelgloed.", methodTitle: "Zo wordt de schatting gemaakt", methodText: "De NPF route gebruikt diafragma, brandpuntsafstand, pixelpitch en declinatie om zichtbare sterrenbeweging op pixelniveau te schatten. De 500 regel gebruikt alleen brandpuntsafstand en sensorcropfactor. Beide zijn geometrische heuristieken voor een camera zonder tracking. Met een trackingmontering gebruikt het plan je ingevoerde belichting en certificeert het de montering niet.", limitsTitle: "Limiet in het veld", limitsText: "Tracking, een heldere hemel, een uitsnede met hoge resolutie, wind of focusdrift kan de praktische belichting veranderen. Maak een testframe en beoordeel hoeken, histogram en montering.", startingStatus: "Invoer controleren", formulaLabel: "Referentieformules", formulaNpf: "NPF: (16,9 x diafragma + 0,10 x brandpuntsafstand + 13,7 x pixelpitch) / (brandpuntsafstand x cosinus declinatie).", formula500: "500 regel: 500 / (brandpuntsafstand x sensorcropfactor).", presetsLabel: "Snelle instellingen", presets: { milkyWay: "24 mm full frame", wideAngle: "14 mm groothoek", telephoto: "85 mm telelens" },
  },
  seo: [
    { type: "title", text: "Waarom een belichtingsstack een limiet nodig heeft", level: 2 },
    { type: "paragraph", html: "Een belichtingsstack bestaat uit losse frames die later worden uitgelijnd en gecombineerd. Zo verzamel je meer signaal terwijl elk frame bruikbaar blijft. Bij een vaste camera maken te lange belichtingen sterren langwerpig door de schijnbare beweging van de hemel. Te korte frames maken de sessie inefficiënt door leesruis en opslagtijd." },
    { type: "paragraph", html: "Deze planner vergelijkt NPF met de 500 regel, deelt de gewenste integratie op in volledige frames en telt de dode tijd tussen bestanden op bij de veldtijd. Het laatste frame kan de gewenste duur iets overschrijden omdat een deel van een frame niet kan worden gemaakt." },
    { type: "list", items: ["Gebruik NPF als diafragma en pixelpitch bekend zijn.", "Gebruik de 500 regel als snelle vergelijking met sensorcrop.", "Zie het aantal frames als echte belasting voor opslag en selectie.", "Maak een testframe voordat je de volledige stack start."] },
    { type: "tip", title: "Een limiet is geen garantie", html: "Controleer heldere sterren en hoeken op volledige resolutie. Wind, coma, focusdrift en trillingen kunnen zwaarder wegen dan de formule." },
    { type: "title", text: "NPF en de 500 regel beantwoorden verschillende vragen", level: 2 },
    { type: "paragraph", html: "De 500 regel is snel en gebruikt de cropfactor van de sensor, maar niet pixelpitch, diafragma of declinatie. NPF voegt deze waarden toe en past beter bij een specifieke camera en lens, maar blijft een heuristiek voor een camera zonder tracking." },
    { type: "title", text: "Zo maak je van het resultaat een nachtsessie", level: 2 },
    { type: "paragraph", html: "Voer de echte waarden in van de apparatuur die je meeneemt. Gebruik geen equivalente brandpuntsafstand als de echte brandpuntsafstand en het sensorformaat al apart zijn ingevoerd. Gebruik voor pixelpitch de juiste modelspecificatie." },
    { type: "list", items: ["Bekijk de hoeken van een testframe op honderd procent.", "Controleer histogram en uitgebeten hooglichten.", "Houd focus en instellingen constant.", "Plan tijd voor dark frames en kalibratie."] },
    { type: "title", text: "Wat verandert er met een trackingmontering", level: 2 },
    { type: "paragraph", html: "Met tracking gebruikt de tool de ingevoerde belichting per frame om het aantal frames te berekenen. NPF en de 500 regel blijven zichtbaar als vergelijking zonder tracking, maar bepalen niet langer de framecount. Pooluitlijning, periodieke fout, guiding, wind, hemelgloed en verzadiging kunnen de nieuwe limiet worden." },
    { type: "tip", title: "Eerst testen, dan de volledige stack", html: "Maak een korte testserie, vergroot de hoeken en controleer de sterren. Pas de gevolgde belichting aan voordat je twee uur donkere hemel vastlegt." },
    { type: 'paragraph', html: 'Een voorbeeld maakt het verschil duidelijk: bij 35 mm, APS C, 5,9 micrometer en 5 graden declinatie ligt de NPF grens rond 3,8 seconden. Zonder tracking zijn voor twee uur ongeveer 1.907 beelden nodig. Met een volgmontering en 120 seconden per beeld zijn 60 beelden genoeg; vijf seconden wachttijd per beeld voegen slechts vijf minuten veldtijd toe.' },
    { type: 'paragraph', html: 'Houd integratietijd en werkelijke sessieduur apart. Schrijfpauzes, controle van de scherpstelling, dithering, batterijwissels en afgekeurde beelden horen in de nachtplanning, ook als ze geen signaal toevoegen. Bij veel korte beelden kan een elektronische sluiter mechanische slijtage verminderen, maar buffer en opslagruimte moeten nog steeds worden gecontroleerd.' },
    { type: 'tip', title: 'Controleer pixelgrootte en sensor', html: 'APS C met 5,9 micrometer is ongebruikelijk voor moderne camera s met hoge resolutie. Als de echte pixel kleiner is, wordt de NPF grens korter. Controleer het exacte cameramodel en maak een testbeeld voordat je de volledige reeks start.' },
  ],
  faq: [
    { question: "Moet ik NPF of de 500 regel gebruiken?", answer: "Gebruik NPF als camera specifieke startwaarde wanneer diafragma en pixelpitch bekend zijn. Gebruik de 500 regel als snelle vergelijking en test beide resultaten op volledige resolutie." },
    { question: "Wat bevat het aantal frames?", answer: "Het telt volledige lichtframes die nodig zijn om de gewenste integratie te bereiken of iets te overschrijden. Darks, flats, bias, pauzes en afgekeurde beelden zijn niet inbegrepen." },
    { question: "Berekent tracking de nauwkeurigheid van guiding?", answer: "Nee. De modus gebruikt de ingevoerde gevolgde belichting. Uitlijning, guiding en hemelgloed moeten met testframes worden gecontroleerd." },
  ],
  howTo: [
    { name: "Voer camerageometrie in", text: "Vul brandpuntsafstand, diafragma, pixelpitch en declinatie in." },
    { name: "Kies de modus", text: "Kies zonder tracking NPF of de 500 regel, of activeer tracking en stel de belichting per frame in." },
    { name: "Stel integratie in", text: "Voer de nuttige totale tijd in en bekijk frames en veldtijd." },
    { name: "Valideer in het veld", text: "Maak een testframe, controleer sterren en histogram en pas de reeks aan." },
  ],
});
