import { createLocalizedContent } from '../localized';

export const content = createLocalizedContent({
  slug: 'planer-stosowania-ekspozycji-astrofotografii',
  title: 'Planer stosowania ekspozycji w astrofotografii',
  description: 'Planuj sesje astrofotograficzne z limitem NPF i regułą 500, liczbą klatek, całkowitą integracją oraz czasem w terenie.',
  ui: {
    cameraLegend: 'Geometria aparatu', focalLabel: 'Ogniskowa', focalHelp: 'Ogniskowa obiektywu lub teleskopu w mm', apertureLabel: 'Przysłona', apertureHelp: 'Użyj liczby f, na przykład 2,8', pixelPitchLabel: 'Rozmiar piksela', pixelPitchHelp: 'Fizyczny rozmiar fotopiksela w mikrometrach', declinationLabel: 'Deklinacja celu', declinationHelp: 'Wpisz bezwzględną deklinację w stopniach', sensorLabel: 'Format matrycy', sensorOptions: { fullFrame: 'Pełna klatka', apsC: 'APS C', microFourThirds: 'Micro Four Thirds', phone: 'Matryca telefonu' },
    ruleLabel: 'Limit ekspozycji', ruleNpf: 'Wzór NPF', rule500: 'Reguła 500', trackingLabel: 'Stan montażu', untracked: 'Bez śledzenia', tracked: 'Montaż ze śledzeniem', trackingExposureLabel: 'Ekspozycja na klatkę ze śledzeniem', trackingExposureHelp: 'Używane tylko z montażem ze śledzeniem. Zacznij od 30 do 120 s i sprawdź klatki testowe.', deadTimeLabel: 'Przerwa między klatkami', deadTimeHelp: 'Zacznij od około 2 s i dopasuj do bufora, zapisu karty oraz interwału aparatu.', totalIntegrationLabel: 'Żądana całkowita integracja', totalIntegrationHelp: 'Użyteczny czas ekspozycji, który chcesz zebrać', resultTitle: 'Twój plan zdjęć', resultKicker: 'Punkt wyjścia na tę noc', secondsUnit: 'na klatkę', framesLabel: 'klatek', totalTimeLabel: 'Planowana integracja', sessionTimeLabel: 'Szacowany czas w terenie', gainLabel: 'Idealny zysk stosowania', sessionDetail: 'Uwzględnia {dead} między klatkami: {deadTotal} czasu przerw.', workloadText: '{frames} cykli migawki. Szacunek czasu w terenie zawiera przerwy między klatkami.', highWorkloadText: '{frames} cykli migawki. Rozważ migawkę elektroniczną, dodatkowe baterie i miejsce na dane. Szacowany czas: {session}.', sensorPixelWarning: 'Sprawdź specyfikację aparatu: {pixel} to duży rozmiar piksela dla APS C i może skrócić limit NPF.', comparisonTitle: 'Dwa limity, jedna decyzja', npfLabel: 'Limit NPF', rule500Label: 'Limit reguły 500', deltaLabel: 'Różnica NPF', timelineTitle: 'Stos jako pasmo światła', timelineStart: 'pierwsza klatka', timelineEnd: 'ostatnia klatka', trackingNote: 'Śledzenie jest aktywne. Plan używa {ceiling} na klatkę, czyli {frames} klatek i około {session} w terenie. Sprawdź ten czas za pomocą ustawienia polarnego, guidingu i klatki testowej; NPF pozostaje porównaniem bez śledzenia.', untrackedNote: 'Użyj {ceiling} jako limitu początkowego, a następnie sprawdź klatkę testową w pełnej rozdzielczości pod kątem kształtu gwiazd i jasności nieba.', methodTitle: 'Jak powstaje szacunek', methodText: 'Ścieżka NPF używa przysłony, ogniskowej, rozmiaru piksela i deklinacji, aby oszacować widoczny ruch gwiazd na poziomie piksela. Reguła 500 używa tylko ogniskowej i współczynnika przycięcia matrycy. Obie są geometrycznymi heurystykami dla aparatu bez śledzenia. Przy montażu ze śledzeniem plan używa wpisanej ekspozycji i nie certyfikuje montażu.', limitsTitle: 'Limit w terenie', limitsText: 'Śledzenie, jasne niebo, wycinek o wysokiej rozdzielczości, wiatr lub zmiana ostrości mogą zmienić praktyczną ekspozycję. Zrób klatkę testową i sprawdź narożniki, histogram oraz montaż.', startingStatus: 'Sprawdzanie danych', formulaLabel: 'Wzory referencyjne', formulaNpf: 'NPF: (16,9 x przysłona + 0,10 x ogniskowa + 13,7 x rozmiar piksela) / (ogniskowa x cosinus deklinacji).', formula500: 'Reguła 500: 500 / (ogniskowa x współczynnik przycięcia matrycy).', presetsLabel: 'Szybkie ustawienia', presets: { milkyWay: '24 mm pełna klatka', wideAngle: '14 mm szeroki kąt', telephoto: '85 mm teleobiektyw' },
  },
  seo: [
    { type: 'title', text: 'Dlaczego stos ekspozycji potrzebuje limitu', level: 2 },
    { type: 'paragraph', html: 'Stos ekspozycji to osobne klatki, które później są wyrównywane i łączone. Celem jest zebranie większej ilości sygnału przy zachowaniu użyteczności każdej klatki. Przy nieruchomym aparacie zbyt długa ekspozycja rozciąga gwiazdy przez pozorny ruch nieba. Zbyt krótkie klatki mogą powodować nieefektywność przez szum odczytu i przerwy zapisu.' },
    { type: 'paragraph', html: 'Ten planer zamienia oba wybory w konkretny plan zdjęć. Porównuje limity NPF i reguły 500, dzieli żądaną integrację na pełne klatki oraz dodaje przerwy między plikami do czasu w terenie. Ostatnia klatka może lekko przekroczyć cel, ponieważ aparat nie wykonuje ułamkowej klatki.' },
    { type: 'list', items: ['Użyj NPF, gdy znasz przysłonę i rozmiar piksela.', 'Użyj reguły 500 jako szybkiego porównania z przycięciem matrycy.', 'Traktuj liczbę klatek jako realny koszt pamięci i selekcji.', 'Zrób klatkę testową przed pełnym stosem.'] },
    { type: 'tip', title: 'Limit nie jest gwarancją', html: 'Sprawdź jasne gwiazdy i narożniki w pełnej rozdzielczości. Wiatr, koma, zmiana ostrości i drgania mogą mieć większe znaczenie niż wzór.' },
    { type: 'title', text: 'NPF i reguła 500 odpowiadają na różne pytania', level: 2 },
    { type: 'paragraph', html: 'Reguła 500 jest szybka i uwzględnia współczynnik przycięcia, ale pomija rozmiar piksela, przysłonę i deklinację. NPF dodaje te zmienne i lepiej pasuje do konkretnego aparatu oraz obiektywu, nadal jednak pozostaje heurystyką dla aparatu bez śledzenia.' },
    { type: 'title', text: 'Jak zmienić wynik w nocną sesję', level: 2 },
    { type: 'paragraph', html: 'Wpisz rzeczywiste wartości sprzętu, którego użyjesz. Nie wpisuj ogniskowej ekwiwalentnej, jeśli rzeczywista ogniskowa i format matrycy są już rozdzielone. Rozmiar piksela odczytaj z wiarygodnej specyfikacji modelu.' },
    { type: 'list', items: ['Sprawdź narożniki klatki testowej przy pełnej rozdzielczości.', 'Skontroluj histogram i przepalone światła.', 'Zachowaj stałą ostrość i ustawienia.', 'Zaplanuj czas na darki i kalibrację.'] },
    { type: 'title', text: 'Co zmienia montaż ze śledzeniem', level: 2 },
    { type: 'paragraph', html: 'Po włączeniu śledzenia narzędzie używa wpisanej ekspozycji na klatkę. NPF i reguła 500 pozostają widoczne jako porównanie bez śledzenia, ale nie wyznaczają już liczby plików. Ustawienie polarne, błąd okresowy, guiding, wiatr, jasność nieba i nasycenie mogą stać się nowym limitem.' },
    { type: 'tip', title: 'Najpierw test, potem cały stos', html: 'Wykonaj krótką serię testową, powiększ narożniki i sprawdź gwiazdy. Dostosuj ekspozycję ze śledzeniem przed wykorzystaniem dwóch godzin ciemnego nieba.' },
    { type: 'paragraph', html: 'Przykład pokazuje różnicę: przy 35 mm, APS C, pikselu 5,9 mikrometra i deklinacji 5 stopni limit NPF wynosi około 3,8 sekundy. Bez prowadzenia dwie godziny wymagają około 1 907 klatek. Z montażem śledzącym i czasem 120 sekund na klatkę wystarczy 60 plików; pięć sekund przerwy na klatkę dodaje tylko pięć minut do czasu w terenie.' },
    { type: 'paragraph', html: 'Oddziel czas integracji od rzeczywistej długości sesji. Zapis na kartę, kontrola ostrości, dithering, wymiana akumulatora i odrzucone klatki należą do planu nocy, nawet jeśli nie zwiększają sygnału. Przy tysiącach krótkich klatek elektroniczna migawka może ograniczyć zużycie mechaniczne, ale trzeba sprawdzić bufor i wolne miejsce.' },
    { type: 'tip', title: 'Sprawdź piksel i format sensora', html: 'APS C z pikselem 5,9 mikrometra to nietypowe połączenie w nowoczesnych aparatach o wysokiej rozdzielczości. Jeśli rzeczywisty piksel jest mniejszy, limit NPF będzie krótszy. Sprawdź dokładny model aparatu i wykonaj klatkę testową przed całą serią.' },
  ],
  faq: [
    { question: 'Czy używać NPF czy reguły 500?', answer: 'Użyj NPF jako punktu wyjścia bliższego aparatowi, jeśli znasz przysłonę i rozmiar piksela. Reguła 500 jest szybkim porównaniem. Oba wyniki sprawdź w pełnej rozdzielczości.' },
    { question: 'Co obejmuje liczba klatek?', answer: 'To liczba pełnych klatek światła potrzebnych do osiągnięcia lub lekkiego przekroczenia żądanej integracji. Darki, flaty, biasy, przerwy i odrzucone zdjęcia nie są wliczone.' },
    { question: 'Czy tryb śledzenia oblicza dokładność guidingu?', answer: 'Nie. Używa wpisanej ekspozycji ze śledzeniem. Ustawienie, guiding i jasność nieba trzeba sprawdzić na prawdziwych klatkach testowych.' },
  ],
  howTo: [
    { name: 'Wpisz geometrię aparatu', text: 'Wprowadź ogniskową, przysłonę, rozmiar piksela i deklinację celu.' },
    { name: 'Wybierz tryb', text: 'Bez śledzenia wybierz NPF lub regułę 500, a ze śledzeniem ustaw ekspozycję na klatkę.' },
    { name: 'Ustaw integrację', text: 'Wpisz użyteczny czas całkowity i sprawdź liczbę klatek oraz czas w terenie.' },
    { name: 'Zweryfikuj w terenie', text: 'Zrób klatkę testową, sprawdź gwiazdy i histogram, a następnie dostosuj serię.' },
  ],
});
