import { createLocalizedContent } from '../localized';

export const content = createLocalizedContent({
  slug: 'planerare-astrofotografi-exponeringsstack',
  title: 'Planerare för exponeringsstapling inom astrofotografi',
  description: 'Planera astrofotografiska sessioner med NPF och 500 regeln, antal bilder, total integration och verklig tid i fält.',
  ui: {
    cameraLegend: 'Kamerageometri', focalLabel: 'Brännvidd', focalHelp: 'Brännvidd för objektiv eller teleskop i mm', apertureLabel: 'Bländare', apertureHelp: 'Använd f talet, till exempel 2,8', pixelPitchLabel: 'Pixelstorlek', pixelPitchHelp: 'Fotositens fysiska storlek i mikrometer', declinationLabel: 'Målets deklination', declinationHelp: 'Absolut deklination i grader', sensorLabel: 'Sensorformat', sensorOptions: { fullFrame: 'Fullformat', apsC: 'APS C', microFourThirds: 'Micro Four Thirds', phone: 'Telefonsensor' },
    ruleLabel: 'Exponeringsgräns', ruleNpf: 'NPF formel', rule500: '500 regeln', trackingLabel: 'Monteringsläge', untracked: 'Utan följning', tracked: 'Följande montering', trackingExposureLabel: 'Exponering per följande bild', trackingExposureHelp: 'Används bara med följande montering. Börja med 30 till 120 s och kontrollera testbilder.', deadTimeLabel: 'Dödtid mellan bilder', deadTimeHelp: 'Börja med ungefär 2 s och anpassa efter buffert, kortskrivning och intervall.', totalIntegrationLabel: 'Önskad total integration', totalIntegrationHelp: 'Den användbara exponeringstid du vill samla in', resultTitle: 'Din fotograferingsplan', resultKicker: 'En startpunkt för natten', secondsUnit: 'per bild', framesLabel: 'bilder', totalTimeLabel: 'Planerad integration', sessionTimeLabel: 'Beräknad tid i fält', gainLabel: 'Idealisk stackingvinst', sessionDetail: 'Inkluderar {dead} mellan bilder: {deadTotal} intervalltid.', workloadText: '{frames} slutarcykler. Fälttiden inkluderar dödtiden mellan bilder.', highWorkloadText: '{frames} slutarcykler. Överväg elektronisk slutare, extra batterier och lagring. Beräknad fälttid: {session}.', sensorPixelWarning: 'Kontrollera kamerans specifikation: {pixel} är en stor pixelstorlek för APS C och kan göra NPF gränsen kortare.', comparisonTitle: 'Två gränser, ett val', npfLabel: 'NPF gräns', rule500Label: '500 regelns gräns', deltaLabel: 'NPF skillnad', timelineTitle: 'Stacken som ett ljusband', timelineStart: 'första bilden', timelineEnd: 'sista bilden', trackingNote: 'Följning är aktiv. Planen använder {ceiling} per bild, alltså {frames} bilder och ungefär {session} i fält. Kontrollera tiden med polinställning, guidning och en testbild; NPF är fortfarande jämförelsen utan följning.', untrackedNote: 'Använd {ceiling} som startgräns och granska en testbild i full upplösning för stjärnform och himmelsljus.', methodTitle: 'Så byggs uppskattningen', methodText: 'NPF vägen använder bländare, brännvidd, pixelstorlek och deklination för att uppskatta när stjärnrörelse syns på pixelnivå. 500 regeln använder bara brännvidd och sensorns cropfaktor. Båda är geometriska tumregler för en kamera utan följning. Med följande montering använder planen den angivna exponeringen och intygar inte monteringens kapacitet.', limitsTitle: 'Gräns i fält', limitsText: 'Följning, ljus himmel, högupplöst beskärning, vind eller fokusdrift kan ändra den praktiska exponeringen. Ta en testbild och kontrollera hörn, histogram och montering.', startingStatus: 'Kontrollerar indata', formulaLabel: 'Referensformler', formulaNpf: 'NPF: (16,9 x bländare + 0,10 x brännvidd + 13,7 x pixelstorlek) / (brännvidd x cosinus för deklination).', formula500: '500 regeln: 500 / (brännvidd x sensorns cropfaktor).', presetsLabel: 'Snabba inställningar', presets: { milkyWay: '24 mm fullformat', wideAngle: '14 mm vidvinkel', telephoto: '85 mm teleobjektiv' },
  },
  seo: [
    { type: 'title', text: 'Varför en exponeringsstack behöver en gräns', level: 2 },
    { type: 'paragraph', html: 'En exponeringsstack består av separata bilder som senare riktas in och kombineras. Målet är att samla mer signal och samtidigt behålla användbara bilder. Med en fast kamera gör en för lång exponering stjärnorna utdragna när himlen rör sig till synes. För korta bilder gör sessionen ineffektiv genom läsbrus och skrivpauser.' },
    { type: 'paragraph', html: 'Den här planeraren gör valen till en konkret fotograferingsplan. Den jämför NPF med 500 regeln, delar den önskade integrationen i hela bilder och lägger till pausen mellan filer i fälttiden. Den sista bilden kan gå något över målet eftersom en kamera inte kan ta en del av en bild.' },
    { type: 'list', items: ['Använd NPF när bländare och pixelstorlek är kända.', 'Använd 500 regeln som snabb jämförelse med sensorbeskärning.', 'Se bildantalet som verklig belastning på lagring och urval.', 'Ta en testbild innan hela stacken startas.'] },
    { type: 'tip', title: 'En gräns är ingen garanti', html: 'Kontrollera ljusa stjärnor och hörn i full upplösning. Vind, koma, fokusdrift och vibrationer kan vara viktigare än formeln.' },
    { type: 'title', text: 'NPF och 500 regeln svarar på olika frågor', level: 2 },
    { type: 'paragraph', html: '500 regeln är snabb och tar hänsyn till sensorns cropfaktor, men inte pixelstorlek, bländare eller deklination. NPF lägger till dessa variabler och passar bättre för en viss kamera och ett visst objektiv, men är fortfarande en tumregel för en kamera utan följning.' },
    { type: 'title', text: 'Så blir resultatet en nattsession', level: 2 },
    { type: 'paragraph', html: 'Skriv in de verkliga värdena för utrustningen du använder. Ange inte motsvarande brännvidd om verklig brännvidd och sensorformat redan är separerade. Använd rätt modelluppgift för pixelstorleken.' },
    { type: 'list', items: ['Granska hörnen i en testbild vid full upplösning.', 'Kontrollera histogram och utfrätta högdagrar.', 'Håll fokus och inställningar konstanta.', 'Planera tid för dark frames och kalibrering.'] },
    { type: 'title', text: 'Vad som ändras med en följande montering', level: 2 },
    { type: 'paragraph', html: 'När följning är vald använder verktyget den angivna exponeringen per bild. NPF och 500 regeln visas som jämförelse utan följning, men bestämmer inte längre antalet filer. Polinställning, periodiskt fel, guidning, vind, himmelsljus och mättnad kan bli den nya gränsen.' },
    { type: 'tip', title: 'Testa först, ta sedan hela stacken', html: 'Ta en kort testserie, förstora hörnen och kontrollera stjärnorna. Justera följande exponering innan du använder två timmar mörk himmel.' },
    { type: 'paragraph', html: 'Ett exempel visar skillnaden: vid 35 mm, APS C, 5,9 mikrometer och 5 graders deklination ligger NPF gränsen nära 3,8 sekunder. Utan följning krävs ungefär 1 907 bilder för två timmar. Med en följande montering och 120 sekunder per bild räcker 60 bilder; fem sekunders paus per bild lägger bara till fem minuter i fältet.' },
    { type: 'paragraph', html: 'Håll integrationstiden åtskild från den verkliga sessionstiden. Skrivpauser, fokuskontroll, dithering, batteribyten och bortsorterade bilder hör till nattens plan även om de inte ökar signalen. Vid många korta exponeringar kan elektronisk slutare minska mekaniskt slitage, men buffert och lagringsutrymme måste fortfarande kontrolleras.' },
    { type: 'tip', title: 'Kontrollera pixel och sensor', html: 'APS C med 5,9 mikrometer är en ovanlig kombination i moderna kameror med hög upplösning. Om den verkliga pixeln är mindre blir NPF gränsen kortare. Kontrollera exakt kameramodell och ta en testbild innan hela serien startas.' },
  ],
  faq: [
    { question: 'Ska jag använda NPF eller 500 regeln?', answer: 'Använd NPF som kameranär startpunkt när bländare och pixelstorlek är kända. Använd 500 regeln för en snabb jämförelse och testa resultatet i full upplösning.' },
    { question: 'Vad ingår i bildantalet?', answer: 'Det räknar hela ljusbilder som behövs för att nå eller lite överskrida önskad integration. Dark, flats, bias, pauser och kasserade bilder ingår inte.' },
    { question: 'Beräknar följningsläget guidningens precision?', answer: 'Nej. Det använder den angivna följande exponeringen. Inställning, guidning och himmelsljus måste kontrolleras med testbilder.' },
  ],
  howTo: [
    { name: 'Skriv in kamerageometri', text: 'Ange brännvidd, bländare, pixelstorlek och målets deklination.' },
    { name: 'Välj läge', text: 'Välj NPF eller 500 regeln utan följning, eller aktivera följning och ange exponeringen per bild.' },
    { name: 'Ange integration', text: 'Skriv in den användbara totaltiden och läs av bilder och fälttid.' },
    { name: 'Validera i fält', text: 'Ta en testbild, kontrollera stjärnor och histogram och ändra serien.' },
  ],
});
