import { createLocalizedContent } from '../localized';

export const content = createLocalizedContent({
  slug: 'astrofotografi-pozlama-yigin-planlayici',
  title: 'Astrofotoğraf Pozlama Yığını Planlayıcısı',
  description: 'NPF ve 500 kuralı, kare sayısı, toplam entegrasyon ve sahadaki gerçek süreyle astrofotoğraf çekimini planlayın.',
  ui: {
    cameraLegend: 'Kamera geometrisi', focalLabel: 'Odak uzaklığı', focalHelp: 'Lens veya teleskobun mm cinsinden odak uzaklığı', apertureLabel: 'Diyafram', apertureHelp: '2,8 gibi f sayısını kullanın', pixelPitchLabel: 'Piksel aralığı', pixelPitchHelp: 'Fotositin mikrometre cinsinden fiziksel boyutu', declinationLabel: 'Hedef deklinasyonu', declinationHelp: 'Mutlak deklinasyonu derece olarak girin', sensorLabel: 'Sensör biçimi', sensorOptions: { fullFrame: 'Tam kare', apsC: 'APS C', microFourThirds: 'Micro Four Thirds', phone: 'Telefon sensörü' },
    ruleLabel: 'Pozlama sınırı', ruleNpf: 'NPF formülü', rule500: '500 kuralı', trackingLabel: 'Montaj durumu', untracked: 'Takipsiz', tracked: 'Takipli montaj', trackingExposureLabel: 'Takipli kare pozlaması', trackingExposureHelp: 'Yalnızca takipli montaj ile kullanılır. 30 ile 120 saniye arasında başlayın ve test kareleriyle doğrulayın.', deadTimeLabel: 'Kareler arasındaki ölü süre', deadTimeHelp: 'Yaklaşık 2 saniye ile başlayın, sonra tampon, kart yazımı ve aralığa göre ayarlayın.', totalIntegrationLabel: 'İstenen toplam entegrasyon', totalIntegrationHelp: 'Toplamak istediğiniz faydalı pozlama süresi', resultTitle: 'Çekim planınız', resultKicker: 'Gece için bir başlangıç noktası', secondsUnit: 'kare başına', framesLabel: 'kare', totalTimeLabel: 'Planlanan entegrasyon', sessionTimeLabel: 'Sahada tahmini süre', gainLabel: 'İdeal yığın kazancı', sessionDetail: 'Kareler arasında {dead} içerir: aralık süresi {deadTotal}.', workloadText: '{frames} deklanşör çevrimi. Saha tahmini kareler arasındaki ölü süreyi içerir.', highWorkloadText: '{frames} deklanşör çevrimi. Elektronik deklanşör, ek pil ve depolama düşünün. Tahmini saha süresi: {session}.', sensorPixelWarning: 'Kamera özelliklerini kontrol edin: {pixel}, APS C için büyük bir piksel aralığıdır ve NPF sınırını kısaltabilir.', comparisonTitle: 'İki sınır, tek karar', npfLabel: 'NPF sınırı', rule500Label: '500 kuralı sınırı', deltaLabel: 'NPF farkı', timelineTitle: 'Işık şeridi olarak yığın', timelineStart: 'ilk kare', timelineEnd: 'son kare', trackingNote: 'Takip etkin. Plan kare başına {ceiling} kullanıyor; {frames} kare ve sahada yaklaşık {session} gerekiyor. Bu süreyi kutup hizası, guiding ve test karesiyle doğrulayın; NPF takipsiz karşılaştırma olarak kalır.', untrackedNote: 'Başlangıç sınırı olarak {ceiling} kullanın ve yıldız şekli ile gökyüzü parlaklığı için tam çözünürlükte test karesini inceleyin.', methodTitle: 'Tahmin nasıl oluşturulur', methodText: 'NPF yolu, yıldız hareketinin piksel düzeyinde görünür hale geldiği zamanı tahmin etmek için diyafram, odak uzaklığı, piksel aralığı ve hedef deklinasyonunu kullanır. 500 kuralı yalnızca odak uzaklığı ve sensör kırpma katsayısını kullanır. İkisi de takipsiz kamera için geometrik sezgisel yöntemlerdir. Takipli montaj seçildiğinde plan girdiğiniz süreyi kullanır ve montajı onaylamaz.', limitsTitle: 'Sahadaki sınır', limitsText: 'Takip, parlak gökyüzü, yüksek çözünürlüklü kırpma, rüzgâr veya odak kayması pratik pozlamayı değiştirebilir. Test karesi çekin ve köşeleri, histogramı ve montaj davranışını kontrol edin.', startingStatus: 'Girdiler kontrol ediliyor', formulaLabel: 'Referans formüller', formulaNpf: 'NPF: (16,9 x diyafram + 0,10 x odak uzaklığı + 13,7 x piksel aralığı) / (odak uzaklığı x deklinasyon kosinüsü).', formula500: '500 kuralı: 500 / (odak uzaklığı x sensör kırpma katsayısı).', presetsLabel: 'Hızlı ayarlar', presets: { milkyWay: '24 mm tam kare', wideAngle: '14 mm geniş açı', telephoto: '85 mm telefoto' },
  },
  seo: [
    { type: 'title', text: 'Pozlama yığınının neden bir sınıra ihtiyacı var', level: 2 },
    { type: 'paragraph', html: 'Pozlama yığını daha sonra hizalanıp birleştirilen ayrı karelerden oluşur. Amaç, her kareyi kullanılabilir tutarken daha fazla sinyal toplamaktır. Sabit bir kamerada çok uzun pozlama, gökyüzünün görünür hareketi nedeniyle yıldızları uzatır. Çok kısa kareler ise okuma gürültüsü ve kayıt araları nedeniyle oturumu verimsizleştirir.' },
    { type: 'paragraph', html: 'Bu planlayıcı kararları somut bir çekim planına dönüştürür. NPF ile 500 kuralını karşılaştırır, istenen entegrasyonu tam karelere böler ve dosyalar arasındaki ölü süreyi saha süresine ekler. Kamera kare parçası çekemediği için son kare hedefi biraz aşabilir.' },
    { type: 'list', items: ['Diyaframı ve piksel aralığını biliyorsanız NPF kullanın.', 'Sensör kırpmasını içeren hızlı karşılaştırma için 500 kuralını kullanın.', 'Kare sayısını depolama ve eleme için gerçek bir yük olarak görün.', 'Tam yığından önce bir test karesi çekin.'] },
    { type: 'tip', title: 'Sınır garanti değildir', html: 'Parlak yıldızları ve köşeleri tam çözünürlükte kontrol edin. Rüzgâr, koma, odak kayması ve titreşim formülden daha önemli olabilir.' },
    { type: 'title', text: 'NPF ve 500 kuralı farklı soruları yanıtlar', level: 2 },
    { type: 'paragraph', html: '500 kuralı hızlıdır ve sensör kırpma katsayısını dikkate alır, ancak piksel aralığını, diyaframı veya deklinasyonu kullanmaz. NPF bu değişkenleri ekler ve belirli bir kamera ile lense daha iyi uyar, fakat takipsiz kamera için yine de bir sezgisel yöntemdir.' },
    { type: 'title', text: 'Sonucu gece oturumuna dönüştürme', level: 2 },
    { type: 'paragraph', html: 'Sahada kullanacağınız ekipmanın gerçek değerlerini girin. Gerçek odak uzaklığı ve sensör biçimi ayrı girilmişse eşdeğer odak uzaklığını tekrar kullanmayın. Piksel aralığı için kamera modelinin doğru teknik bilgisini kullanın.' },
    { type: 'list', items: ['Test karesinin köşelerini tam çözünürlükte inceleyin.', 'Histogramı ve kırpılmış parlak alanları kontrol edin.', 'Odak ve ayarları sabit tutun.', 'Karanlık kareler ve kalibrasyon için zaman ayırın.'] },
    { type: 'title', text: 'Montaj takip ettiğinde ne değişir', level: 2 },
    { type: 'paragraph', html: 'Takip seçildiğinde araç kare başına girdiğiniz takipli pozlamayı kullanır. NPF ve 500 kuralı takipsiz karşılaştırma olarak görünür, ancak kare sayısını belirlemez. Kutup hizası, periyodik hata, guiding, rüzgâr, gökyüzü parlaklığı ve doygunluk yeni sınır olabilir.' },
    { type: 'tip', title: 'Önce test, sonra tam yığın', html: 'Kısa bir test serisi çekin, köşeleri büyütün ve yıldızları kontrol edin. İki saatlik karanlık gökyüzüne başlamadan önce takipli pozlamayı ayarlayın.' },
    { type: 'paragraph', html: 'Bir örnek farkı gösterir: 35 mm, APS C, 5,9 mikrometre ve 5 derece deklinasyonda NPF sınırı yaklaşık 3,8 saniyedir. Takipsiz iki saat için yaklaşık 1.907 kare gerekir. Takipli montajda kare başına 120 saniye kullanılırsa 60 kare yeterlidir; kare başına beş saniyelik bekleme saha süresine yalnızca beş dakika ekler.' },
    { type: 'paragraph', html: 'Entegrasyon süresini gerçek oturum süresinden ayrı değerlendirin. Karta yazma, odak kontrolü, dithering, pil değişimi ve reddedilen kareler sinyale katkı sağlamasa da gece planına dahildir. Çok sayıda kısa karede elektronik deklanşör mekanik yıpranmayı azaltabilir, ancak tampon ve depolama kapasitesi yine de kontrol edilmelidir.' },
    { type: 'tip', title: 'Piksel aralığını ve sensörü kontrol edin', html: 'APS C ile 5,9 mikrometre, yüksek çözünürlüklü modern makinelerde alışılmadık bir birleşimdir. Gerçek piksel daha küçükse NPF sınırı kısalır. Kesin kamera modelini doğrulayın ve tüm seriden önce bir test karesi çekin.' },
  ],
  faq: [
    { question: 'NPF mi yoksa 500 kuralı mı kullanılmalı?', answer: 'Diyaframı ve piksel aralığını biliyorsanız kameraya daha yakın başlangıç için NPF kullanın. 500 kuralı hızlı karşılaştırmadır; sonucu tam çözünürlükte test edin.' },
    { question: 'Kare sayısı neyi içerir?', answer: 'İstenen entegrasyona ulaşmak veya biraz aşmak için gereken tam ışık karelerini sayar. Karanlık, düz, bias, aralık ve reddedilen kareler dahil değildir.' },
    { question: 'Takip modu guiding doğruluğunu hesaplar mı?', answer: 'Hayır. Girdiğiniz takipli pozlama süresini kullanır. Hizalama, guiding ve gökyüzü parlaklığı gerçek test kareleriyle kontrol edilmelidir.' },
  ],
  howTo: [
    { name: 'Kamera geometrisini girin', text: 'Odak uzaklığı, diyafram, piksel aralığı ve hedef deklinasyonunu girin.' },
    { name: 'Modu seçin', text: 'Takipsiz NPF veya 500 kuralını seçin, ya da takibi etkinleştirip kare süresini belirleyin.' },
    { name: 'Entegrasyonu ayarlayın', text: 'Faydalı toplam süreyi girin ve kare sayısı ile saha süresini okuyun.' },
    { name: 'Sahada doğrulayın', text: 'Test karesi çekin, yıldızları ve histogramı kontrol edin, sonra seriyi ayarlayın.' },
  ],
});
